[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv = { version = "0.6.0", path = "../cv" }
cv-reconstruction = { version = "0.1.0", path = "../cv-reconstruction", features = ["serde-serialize"] }
structopt = "0.3.20"
serde = { version = "1.0.117", features = ["derive"] }
image = "0.23.12"
rand = "0.7.3"
rand_pcg = "0.2.1"
log = "0.4.11"
pretty_env_logger = "0.4.0"
bincode = "1.3.1"
serde_json = "1.0.59"

kas = { git="https://github.com/kas-gui/kas.git" }
kas-wgpu = { git="https://github.com/kas-gui/kas.git" }
kas-theme = { git="https://github.com/kas-gui/kas.git" }
bytemuck = "1.2"
cgmath = "0.17.0"
