[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv-core = "0.10.0"
eight-point = "0.4.0"
structopt = "0.3.14"
serde = { version = "1.0.110", features = ["derive"] }
image = "0.23.4"
arrsac = "0.3.0"
rand = "0.7.3"
rand_pcg = "0.2.1"
log = "0.4.8"
space = { version = "0.10.3", features = ["simd-hamming"] }
pretty_env_logger = "0.4.0"
akaze = "0.3.1"
evmap = "10.0.2"
sharded-slab = "0.0.9"
cv-pinhole = "0.1.1"
ply-rs = "0.1.2"
float-ord = "0.2.0"

[profile.release]
lto = true
codegen-units = 1
