[package]
name = "lambda-twist"
version = "0.1.0"
authors = ["Matthieu Pizenberg <matthieu.pizenberg@gmail.com>", "Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Camera pose estimation given 3D points and corresponding pixel coordinates"
documentation = "https://docs.rs/lambda-twist/"
homepage = "https://github.com/rust-cv/p3p"
repository = "https://github.com/rust-cv/p3p"
readme = "README.md"
keywords = ["p3p", "pose", "vision"]
categories = ["computer-vision", "algorithms", "science::robotics", "no-std"]
license = "MPL-2.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
cv-core = "0.10.0"

[dev-dependencies]
approx = "0.3.2"
arrsac = "0.3.0"
rand = { version = "0.7.3", features = ["small_rng"] }
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
itertools = "0.9.0"
arraymap = "0.1.1"
cv-pinhole = "0.1.1"
