[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
vslam = { path = "../vslam", version = "0.1.0" }
vslam-akaze = { path = "../vslam-akaze", version = "0.1.0" }
