[package]
name = "cv-pinhole"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Pinhole camera model"
documentation = "https://docs.rs/cv-pinhole/"
repository = "https://github.com/rust-cv/cv-pinhole"
keywords = ["computer", "vision", "pinhole", "camera", "calibration"]
categories = ["algorithms", "computer-vision", "no-std", "science::robotics"]
license = "MIT"
readme = "README.md"

[dependencies]
cv-core = "0.10.0"
derive_more = "0.99.5"
num-traits = { version = "0.2.11", default-features = false }
