[package]
name = "akaze"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.0"
rand = "0.7.3"
log = "0.4.8"
primal = "0.2.3"
scoped_threadpool = "0.1.9"
num_cpus = "1.12.0"
nalgebra = "0.20.0"

[dev-dependencies]
approx = "0.3.2"
