[package]
name = "eight-point"
version = "0.5.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Eight-point algorithm for essential matrix estimation"
documentation = "https://docs.rs/eight-point/"
repository = "https://github.com/rust-cv/eight-point"
keywords = ["hartly", "zisserman", "photogrammetry", "eight", "point"]
categories = ["algorithms", "computer-vision", "no-std", "science", "science::robotics"]
license = "MIT"
readme = "README.md"

[dependencies]
float-ord = "0.2.0"
cv-core = "0.11.0"
cv-pinhole = "0.2.0"

[dev-dependencies]
nalgebra = "0.21.0"
cv-geom = "0.1.0"

[profile.dev]
# The tests take a very long time without optimization.
opt-level = 3

