[package]
name = "nister-stewenius"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>", "Chris Sweeney <cmsweeney@cs.ucsb.edu>"]
edition = "2018"
license = "BSD"

[dependencies]
cv-core = { path = "../cv-core" }
float-ord = "0.2.0"

[dev-dependencies]
itertools = "0.8.2"
nalgebra = "0.19.0"
