[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv-core = "0.7.2"
eight-point = "0.2.0"
structopt = "0.2.15"
serde = { version = "1.0.91", features = ["derive"] }
akaze = "0.1.3"
image = "0.23.0"
arrsac = "0.3.0"
rand = "0.7.3"
