[package]
name = "cv-optimize"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
levenberg-marquardt = "0.5.0"
cv-core = "0.12.0"
nalgebra = { version = "0.21.0", features = ["alloc"], default-features = false }
