[package]
name = "akaze"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.0"
log = "0.4.8"
primal = "0.2.3"
scoped_threadpool = "0.1.9"
num_cpus = "1.12.0"
nalgebra = "0.20.0"
cv-core = "0.9.1"

[dev-dependencies]
approx = "0.3.2"
eight-point = "0.3.0"
arrsac = "0.3.0"
cv-core = { version = "0.9.1", features = ["pinhole"] }
space = { version = "0.10.3", features = ["simd"] }
rand = "0.7.3"
rand_pcg = "0.2.1"
env_logger = "0.7.1"
criterion = "0.3.1"

[[bench]]
name = "criterion"
harness = false

[profile.dev]
# The tests take a very long time without optimization.
opt-level = 3

[profile.bench]
codegen-units = 1