[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv = "0.2.0"
structopt = "0.3.14"
serde = { version = "1.0.111", features = ["derive"] }
image = "0.23.4"
rand = "0.7.3"
rand_pcg = "0.2.1"
log = "0.4.8"
pretty_env_logger = "0.4.0"
evmap = "10.0.2"
sharded-slab = "0.0.9"
ply-rs = "0.1.2"
float-ord = "0.2.0"

[profile.release]
lto = true
codegen-units = 1
