[package]
name = "cv"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Batteries-included pure-Rust computer vision crate"
keywords = ["computer", "vision", "photogrammetry", "camera"]
categories = ["computer-vision"]
repository = "https://github.com/rust-cv/cv"
documentation = "https://docs.rs/cv/"
license = "MIT"
readme = "README.md"

[features]
default = [
    "alloc",
    "cv-pinhole",
    "cv-geom",
    "eight-point",
    "lambda-twist",
    "akaze",
    "space",
    "hnsw",
    "levenberg-marquardt",
    "arrsac",
    "bitarray",
]
alloc = [
    "cv-core/alloc"
]

[dependencies]
cv-core = { git = "https://github.com/rust-cv/cv-core.git" }
cv-pinhole = { git = "https://github.com/rust-cv/cv-pinhole.git", optional = true }
cv-geom = { git = "https://github.com/rust-cv/cv-geom.git", optional = true }
eight-point = { git = "https://github.com/rust-cv/eight-point.git", optional = true }
lambda-twist = { git = "https://github.com/rust-cv/lambda-twist.git", optional = true }
akaze = { git = "https://github.com/rust-cv/akaze.git", optional = true }
space = { version = "0.10.3", optional = true }
hnsw = { version = "0.6.1", optional = true }
levenberg-marquardt = { version = "0.5.0", optional = true }
arrsac = { version = "0.4.0", optional = true }
bitarray = { version = "0.2.2", features = ["space"], optional = true }
