[workspace]

members = [
    "cv",
    "cv-core",
    "cv-geom",
    "cv-pinhole",
    "cv-optimize",
    "akaze",
    "eight-point",
    "lambda-twist",
    "kpshow",
    "nister-stewenius",
    "vslam-sandbox",
    "cv-reconstruction",
]
