[package]
name = "cv-pinhole"
version = "0.6.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "Pinhole camera model for comptuer vision"
documentation = "https://docs.rs/cv-pinhole/"
repository = "https://github.com/rust-cv/cv-pinhole"
keywords = ["computer", "vision", "pinhole", "camera", "calibration"]
categories = ["algorithms", "computer-vision", "no-std", "science::robotics"]
license = "MIT"
readme = "README.md"

[features]
default = ["alloc"]
alloc = []

[dependencies]
cv-core = "0.15.0"
derive_more = "0.99.8"
num-traits = { version = "0.2.12", default-features = false }
float-ord = "0.2.0"

[dev-dependencies]
cv-geom = "0.6.0"

[package.metadata.docs.rs]
all-features = true
