[package]
name = "cv-pinhole"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv-core = "0.10.0"
derive_more = "0.99.5"
num-traits = { version = "0.2.11", default-features = false }
