[package]
name = "kpdraw"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
akaze = { version = "0.7.0", path = "../akaze" }
structopt = "0.3.20"
image = { version = "0.23.12", features = ["png", "jpeg"] }
imageproc = "0.22.0"
