[package]
name = "cv-optimize"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
levenberg-marquardt = "0.6.0"
cv-core = { version = "0.15.0", path = "../cv-core" }
nalgebra = { version = "0.22.0", features = ["alloc"], default-features = false }
num-traits = "0.2.12"
argmin = { git = "https://github.com/vadixidav/argmin.git", rev = "847188f7581a19a2a61d764711d47f0214ae49b4", features = ["nalgebral"] }
average = "0.10.4"
itertools = "0.9.0"
