[package]
name = "imgshow"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
iced = { version = "0.3.0", features = ["image"] }
structopt = "0.3.22"
iced_native = "0.4.0"
image = "0.23.14"
