# Cargo test

on:
  push:
    branches:
      - master
  pull_request:

name: build

jobs:
  test:
    name: Build All
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get -y install libxkbcommon-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-features
