# This ensures we can build with no-std.

on: [push, pull_request]

name: no-std

jobs:
  build:
    - name: Ensure that crate is no_std
      uses: actions-rs/cargo@v1
      with:
        command: rustc
        args: --manifest-path=ensure_no_std/Cargo.toml -- -C link-arg=-nostartfiles